# Modified from AionCore by WINK GO contributors in 2026.
[package]
name = "winkgo-auth"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
winkgo-common.workspace = true
winkgo-db.workspace = true
winkgo-api-types.workspace = true
jsonwebtoken.workspace = true
bcrypt.workspace = true
tower.workspace = true
tower-http.workspace = true
dashmap.workspace = true
axum.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
getrandom.workspace = true
base64.workspace = true
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true
http-body-util.workspace = true
tower = { workspace = true, features = ["util"] }
